<a href="https://colab.research.google.com/github/tithisultana/Project/blob/main/M_12_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***1. Project Overview***

**Diabetes Prediction Using Logistic Regression**

This project aims to develop a machine learning model that predicts whether a person is diabetic or non-diabetic based on several medical and demographic features. The dataset contains the following attributes: Preg, Plas, Pres, Skin, Test, Mass, Pedi, Age, with Class as the target variable. Logistic Regression is used as the classification algorithm to learn the relationship between these features and the diabetes outcome.

**2. Problem Statement**

Diabetes is a common health condition that can affect a person's overall health and may lead to various complications. Early prediction can help identify individuals who may be at risk.

The objective of this project is to develop a machine learning model that can predict whether a person is diabetic or non-diabetic using medical information such as pregnancy count, plasma glucose concentration, blood pressure, skin thickness, insulin level, BMI, diabetes pedigree function, and age.

The model uses Logistic Regression to classify the patients into two categories:

0 → Non-Diabetic
1 → Diabetic

**3. Learning Objectives**

To develop a Logistic Regression model that predicts whether a person is diabetic or non-diabetic based on medical and demographic features.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
df = pd.read_csv('/content/2026-06-22T16-08-10.976Z-pima-indians-diabetes - pima-indians-diabetes.csv')

In [ ]:
df.shape

(768, 9)

In [ ]:
df.head(2)

   Preg  Plas  Pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Preg    768 non-null    int64
 1   Plas    768 non-null    int64
 2   Pres    768 non-null    int64
 3   skin    768 non-null    int64
 4   test    768 non-null    int64
 5   mass    768 non-null    float64
 6   pedi    768 non-null    float64
 7   age     768 non-null    int64
 8   class   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
df.describe()

,Preg,Plas,Pres,skin,test,mass,pedi,age,class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df.isnull().sum()

Preg     0
Plas     0
Pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

# Zero counts

In [ ]:
feature_cols = [col for col in df.columns if col != 'class']
zero_counts = (df[feature_cols] == 0).sum()
print(zero_counts)

Preg    111
Plas      5
Pres     35
skin    227
test    374
mass     11
pedi      0
age       0
dtype: int64

In [ ]:
feature_cols = [col for col in df.columns if col != 'class']
type(feature_cols)

list

In [ ]:
corr = df.corr()
corr.round(2)

       Preg  Plas  Pres  skin  test  mass  pedi   age  class
Preg   1.00  0.13  0.14 -0.08 -0.07  0.02 -0.03  0.54   0.22
Plas   0.13  1.00  0.15  0.06  0.33  0.22  0.14  0.26   0.47
Pres   0.14  0.15  1.00  0.21  0.09  0.28  0.04  0.24   0.07
skin  -0.08  0.06  0.21  1.00  0.44  0.39  0.18 -0.11   0.07
test  -0.07  0.33  0.09  0.44  1.00  0.20  0.19 -0.04   0.13
mass   0.02  0.22  0.28  0.39  0.20  1.00  0.14  0.04   0.29
pedi  -0.03  0.14  0.04  0.18  0.19  0.14  1.00  0.03   0.17
age    0.54  0.26  0.24 -0.11 -0.04  0.04  0.03  1.00   0.24
class  0.22  0.47  0.07  0.07  0.13  0.29  0.17  0.24   1.00

In [ ]:
class_counts = df['class'].value_counts().sort_index()
class_counts

class
0    500
1    268
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x = df.drop('class', axis =1)
y = df['class']
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3,random_state=1)

# MEAN THE ZERO VALUES

In [ ]:
from sklearn.impute import SimpleImputer
rep_o = SimpleImputer(missing_values = 0, strategy = 'mean')
colm = x_train.columns
x_train = pd.DataFrame(rep_o.fit_transform(x_train), columns = colm)
x_test = pd.DataFrame(rep_o.transform(x_test), columns = colm)
print(x_train.head())

        Preg   Plas  Pres  skin        test  mass   pedi   age
0  15.000000  136.0  70.0  32.0  110.000000  37.1  0.153  43.0
1   4.396514   97.0  64.0  36.0  100.000000  36.8  0.600  25.0
2   1.000000  116.0  70.0  28.0  158.243346  27.4  0.204  21.0
3   2.000000  106.0  64.0  35.0  119.000000  30.5  1.400  34.0
4   4.396514  123.0  88.0  37.0  158.243346  35.2  0.197  29.0

In [ ]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver = 'liblinear')
model.fit(x_train,y_train)
y_predict = model.predict(x_test)

coef_df = pd.DataFrame(model.coef_, columns = colm)
coef_df['intercept'] = model.intercept_
coef_df.index = ['coefficient']
(coef_df.round(4))

,Preg,Plas,Pres,skin,test,mass,pedi,age,intercept
coefficient,0.1246,0.0262,-0.0298,-0.0125,-0.0001,0.0732,0.3592,0.0125,-4.8909

In [ ]:
model_score = model.score(x_test, y_test)
print(f"Model accuracy : {model_score:.4f}, {model_score*100:.2f}%")

Model accuracy : 0.7792, 77.92%

In [ ]:
cm = metrics.confusion_matrix(y_test,y_predict,labels = (1,0))
cm

array([[ 48,  37],
       [ 14, 132]])